eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:<password>@mongodb-cluster.z6oprjs.mongodb.net/
      host: mongodb-cluster.z6oprjs.mongodb.net
      port: 27017
      database: orderdb
      repositories:
        enabled: true
